services:
  nginx:
    image: nginx:trixie
    network_mode: "host"
    # networks:
    #   - infra
    # ports:
    #   - "80:80"
    #   - "443:443"
    #   - "443:443/udp"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./tls:/tls
      - ./www:/var/www
    restart: always
