networks:
  infra:
    external: true

services:
  nginx:
    image: nginx:trixie
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/snippets:/etc/nginx/snippets
      - ./letsencrypt:/etc/letsencrypt
      - ./www:/var/www
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: always
